package Winappdriver.TestWinApp;
import java.net.URL;
import org.openqa.selenium.By;
import java.net.MalformedURLException;
import java.util.concurrent.TimeUnit;
import io.appium.java_client.windows.WindowsDriver;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TestOneOutlookLaunch {

	public static void main(String[] args) throws MalformedURLException, Throwable 
	{

		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("app", "C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE");
		/* capabilities.setCapability("app", "Microsoft.WindowsMaps_8wekyb3d8bbwe!App");
		 capabilities.setCapability("app", "Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}");
		 capabilities.setCapability("app", "Microsoft.Office.EXCEL.EXE.15");
		 capabilities.setCapability("app", "Microsoft.Office.ONENOTE.EXE.15");
		 capabilities.setCapability("app", "Microsoft.Office.WINWORD.EXE.15");
		 capabilities.setCapability("app", "Microsoft.Windows.Explorer");
		 capabilities.setCapability("app", "Microsoft.MSPaint_8wekyb3d8bbwe!Microsoft.MSPaint");
		 capabilities.setCapability("app", "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App");
		 capabilities.setCapability("app", "Microsoft.WindowsNotepad_8wekyb3d8bbwe!App");  */


		capabilities.setCapability("platformName", "Windows");
		capabilities.setCapability("platformVersion", "1.0");
		WindowsDriver driver = new WindowsDriver(new URL("http://127.0.0.1:4723"), capabilities);
		//System.out.println(driver.getSessionId());
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

		/*driver.findElementByAccessibilityId("NewItem").click();
		System.out.println("New Mail item opened"); */
		driver.findElementByAccessibilityId("FileTabButton").click();
		System.out.println("User clicked on File button and went to File menu");
		Thread.sleep(2000);
		driver.findElementByName("Back").click();
		System.out.println("User came back to mailbox");
		//driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
		Thread.sleep(2000);
		driver.findElementByName("Close").click();
		System.out.println("User closed Outlook");


	}

}
